import type { Metadata } from 'next';
import { Instrument_Sans } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';
import { Toaster } from 'sonner';

const instrumentSans = Instrument_Sans({
	variable: '--font-instrument-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={`${instrumentSans.variable} antialiased`}>
					{children}
					<Toaster position='top-center' richColors theme='dark' />
				</body>
			</html>
		</ClerkProvider>
	);
}
